services:
  remote-ubuntu:
    build:
      context: ./remote-ubuntu
    container_name: remote-ubuntu
    ports:
      - "2222:22"
      - "9100:9100"
    networks:
      - observability-net
    volumes:
      - remote-ubuntu-bin:/usr/local/bin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge

volumes:
  remote-ubuntu-bin:
