server:
  port: 8091

spring:
  application:
    name: event-consumer

  datasource:
    url: jdbc:postgresql://postgres:5432/events_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    consumer:
      group-id: event-group
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
