global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'remote-ubuntu-node'
    static_configs:
      - targets: [ 'remote-ubuntu:9100' ]
