server:
  port: 8090

spring:
  application:
    name: event-producer

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://schema-registry:8081
event:
  topic: events
  generation:
    interval-ms: 1000  # Интервал генерации событий (1 сообщение в секунду)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
